services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.6
    container_name: wefit-mysql-dev
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - "${MYSQLDB_PORT}:3306"
    volumes:
      - ./data/:/var/lib/mysql
    networks:
      - wefit-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQLDB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # NestJS Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wefit-app-dev
    restart: unless-stopped
    env_file: ./.env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:${MYSQLDB_PASSWORD}@mysqldb:3306/${MYSQLDB_DATABASE}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      # Prevent overwriting node_modules
      - /app/node_modules
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - wefit-network
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        npx prisma migrate dev --name init &&
        echo 'Database migrations applied successfully!' &&
        npm run start:dev
      "

networks:
  wefit-network:
    driver: bridge
